language: python
python:
  - "2.7"
env:
  - PPA_VERSION=2.0.2 BINDINGS_VERSION=2.0.1.3
  - PPA_VERSION=2.1.0 BINDINGS_VERSION=2.1.0.1
before_install:
 - echo 'yes' | sudo add-apt-repository ppa:mapnik/v$PPA_VERSION
 - sudo apt-get update -qq
 - sudo aptitude install -y -q10 libmapnik libmapnik-dev mapnik-utils
install:
  - pip install -U mapnik2==$BINDINGS_VERSION --use-mirrors
  - pip install -U . --use-mirrors
  - pip install -r requirements/test.pip --use-mirrors
script: nosetests -v
